name: Compile and Validate

on:
  push:
    branches:
      - 'main'
  release:
    types:
      - published

jobs:
  build:
    name: "Compile Sectorfile"
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download Compiler
        run: |
          curl -L --output compiler https://github.com/VATSIM-UK/sector-file-compiler/releases/latest/download/cli-linux-x64
          chmod +x ./compiler

      - name: Set Build Version
        run: echo "SECTORFILE_BUILD_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Compile
        run: |
          ./compiler --config-file compiler.config.json --strip-comments --no-wait --build-version $SECTORFILE_BUILD_VERSION

      - name: Upload Build As Artifact
        uses: actions/upload-artifact@v2
        with:
          name: UK Sector File
          path: ".build/bin/UK.*"
